---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: default
  labels:
    k8s-app: kube-state-metrics
spec:
  jobLabel: k8s-app-kube-state-metrics
  endpoints:
  - port: http-metrics
    interval: 15s
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  namespaceSelector:
    matchNames:
    - default
