apiVersion: v1
kind: Service
metadata:
  labels:
    app: "prometheus"
    prometheus: "prometheus"
  name: prometheus-prometheus
  namespace: default
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: prometheus
  sessionAffinity: None
  type: NodePort
